### ISSUE TITLE
Need support

### ISSUE THREAD

**Issue by hmnytv** [medvm/widevine_keys#33]
Traceback (most recent call last):
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "D:\widevine\widevine_keys-main\widevine_keys-main\l3.py", line 52, in WV_Function
    data=f'token={headers.token}&provider={headers.provider}&payload={str(request, "utf-8" )}'
AttributeError: module 'headers' has no attribute 'token'

**Comment by omarsoftbox** [comment]
yes. this my err too

**Comment by Essam23** [comment]
Just use the script from this point, it will work with Shahid and OSN.

https://codeload.github.com/medvm/widevine_keys/zip/4b7cd4a479106b295ed767b7cd028ebe9bee92db

or use this file.

[widevine_keys-Shahid.zip](https://github.com/medvm/widevine_keys/files/7737130/widevine_keys-Shahid.zip)

**Comment by omarsoftbox** [comment]
thenks for your helpe. i have sollusion for osn and shahid but not work in
noorplay

https://www.noorplay.com/.
if you have solution for noorplay send me scrypt

**Comment by omarsoftbox** [comment]
license response status: <Response [400]>

server did not issue license, check json params in POST request.

unable to parse license - check protobufs

this my result in shahid
if you have new device_client_id_blob and device_private_key send me .

**Comment by ErrorArabi** [comment]
this my error too...is there any solution ?
<a href="https://ibb.co/kQCvjbN"><img src="https://i.ibb.co/m6WgkZf/gethub.jpg" alt="gethub" border="0"></a>
