### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by f0n1x** [medvm/widevine_keys#77]
Traceback (most recent call last):
  File "/home/user/widevine_keys/l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "/home/user/widevine_keys/l3.py", line 39, in WV_Function
    wvdecrypt = WvDecrypt(init_data_b64=pssh, cert_data_b64=cert_b64, device=deviceconfig.device_android_generic)                   
  File "/home/user/widevine_keys/wvdecryptcustom.py", line 33, in __init__
    self.session = self.cdm.open_session(check_pssh(self.init_data_b64), deviceconfig.DeviceConfig(self.device))
  File "/home/user/widevine_keys/wvdecryptcustom.py", line 19, in check_pssh
    pssh = base64.b64decode(pssh_b64)
  File "/usr/lib64/python3.9/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/lib64/python3.9/base64.py", line 45, in _bytes_from_decode_data
    raise TypeError("argument should be a bytes-like object or ASCII "
TypeError: argument should be a bytes-like object or ASCII string, not 'dict'

Got this error while attempting to derive keys for a show on BYUtv (free) for a friend. Any help would be appreciated.

**Comment by inxsq** [comment]
same problem, anyone can help about this?

**Comment by Chris230291** [comment]
Same here

**Comment by tokland** [comment]
l3.py, try replacing `pssh = get_pssh(MDP_URL)` by `pssh = get_pssh(MDP_URL)["#text"]`. 

Apparently, xmltodict returns a string when the tag has no attributes, but a dict otherwise. The problem appears when it returns a dict.
