### ISSUE TITLE
ValueError: Ciphertext with incorrect length.

### ISSUE THREAD

**Issue by bassamh1977** [medvm/widevine_keys#79]
Hello ,
I ran the l3.py eyerything looks good and I get the license_content.bin file but I got this error .

```
Traceback (most recent call last):
  File "C:\widevine\l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh)
  File "C:\widevine\l3.py", line 94, in WV_Function
    wvdecrypt.update_license(license_b64)
  File "C:\widevine\wvdecryptcustom.py", line 58, in update_license
    self.cdm.provide_license(self.session, license_b64)
  File "C:\widevine\cdm\cdm.py", line 285, in provide_license
    session.session_key = oaep_cipher.decrypt(license.SessionKey)
  File "C:\Users\PEO.MAD\AppData\Roaming\Python\Python310\site-packages\Cryptodome\Cipher\PKCS1_OAEP.py", line 167, in decrypt
    raise ValueError("Ciphertext with incorrect length.")
ValueError: Ciphertext with incorrect length.
```

I don't know how to solve this issue.

**Comment by it4tk** [comment]
Any one got this error ?

**Comment by Polaris0112** [comment]
same issue. Already change headers.py and update l3.py to support the website.

`Traceback (most recent call last):
  File "/*/widevine_keys/l3.py", line 128, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "/*/widevine_keys/l3.py", line 123, in WV_Function
    wvdecrypt.update_license(license_b64)
  File "/*/widevine_keys/wvdecryptcustom.py", line 58, in update_license
    self.cdm.provide_license(self.session, license_b64)
  File "/*/widevine_keys/cdm/cdm.py", line 285, in provide_license
    session.session_key = oaep_cipher.decrypt(license.SessionKey)
  File "/*/widevine_keys/venv/lib/python3.9/site-packages/Cryptodome/Cipher/PKCS1_OAEP.py", line 167, in decrypt
    raise ValueError("Ciphertext with incorrect length.")
ValueError: Ciphertext with incorrect length.
`
