### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by tatata17** [medvm/widevine_keys#8]
I got the following error.
What is the solution?

```
C:\Users\○○\Desktop\DRM\widevine_keys-main>C:\Users\○○\Desktop\DRM\widevine_keys-main\l3.py
Traceback (most recent call last):
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\l3.py", line 11, in <module>
    from cdm import cdm, deviceconfig
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\cdm.py", line 10, in <module>
    from cdm.formats import wv_proto2_pb2 as wv_proto2
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```

**Comment by medvm** [comment]
@tatata17 
solution:
`C:\Users\○○\Desktop\DRM\widevine_keys-main> py l3.py`

**Comment by RedPenguin2** [comment]
For some reason, I got the exact same error in Windows 10 but it runs immediately on Ubuntu 20.04.

**Comment by tatata17** [comment]
> 

C:\Users\○○\Desktop\DRM\widevine_keys-main>py l3.py
Traceback (most recent call last):
  File "l3.py", line 11, in <module>
    from cdm import cdm, deviceconfig
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\cdm.py", line 10, in <module>
    from cdm.formats import wv_proto2_pb2 as wv_proto2
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

**Comment by tatata17** [comment]
> @ tatata17 ソリューション： `C:\Users\○○\Desktop\DRM\widevine_keys-main>py l3.py`

I try it
```
C:\Users\○○\Desktop\DRM\widevine_keys-main>py l3.py
Traceback (most recent call last):
  File "l3.py", line 11, in <module>
    from cdm import cdm, deviceconfig
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\cdm.py", line 10, in <module>
    from cdm.formats import wv_proto2_pb2 as wv_proto2
  File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```

**Comment by ST02-droid** [comment]
Same problem

**Comment by doxuyenxo** [comment]
I got this error after run "py l3.py" . Any help please. Thanks!
![image](https://user-images.githubusercontent.com/40689346/145672234-1872dfe2-fec7-40aa-aec0-c4294c24c50a.png)

**Comment by arbarbosa1979** [comment]
`py -m pip install --upgrade pip`
`py -m pip install -r requirements.txt`
`py -m pip install pycryptodome`
`py -m pip install pycryptodomex`

**Comment by tatata17** [comment]
> > > @ tatata17じ： `C:\Users\○○\Desktop\DRM\widevine_keys-main>py l3.py`
> > 
> > 
> > 私はそれを試してみました
> > ```
> > C:\Users\○○\Desktop\DRM\widevine_keys-main>py l3.py
> > Traceback (most recent call last):
> >   File "l3.py", line 11, in <module>
> >     from cdm import cdm, deviceconfig
> >   File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\cdm.py", line 10, in <module>
> >     from cdm.formats import wv_proto2_pb2 as wv_proto2
> >   File "C:\Users\○○\Desktop\DRM\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
> >     _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
> > AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
> > ```
> 
> `py -m pip install --upgrade pip` `py -m pip install -r requirements.txt` `py -m pip install pycryptodome` `py -m pip install pycryptodomex`

I tried it but didn't work

**Comment by medvm** [comment]
idk what's your error message, show screenshot

**Comment by tatata17** [comment]
![image](https://user-images.githubusercontent.com/88437066/145979316-ca558090-c4ce-4426-aa9f-74ed4e69c5c4.png)

**Comment by tatata17** [comment]
![image](https://user-images.githubusercontent.com/88437066/145979445-467df6b8-3b91-442b-b2ce-46f1340202d4.png)

**Comment by tatata17** [comment]
```
Microsoft Windows [Version 10.0.19042.1348]
(c) Microsoft Corporation. All rights reserved.

C:\Users\"My name"\Desktop\DRM\widevine_keys-main>py -m pip install --upgrade pip
Requirement already satisfied: pip in c:\python38\lib\site-packages (21.3.1)

C:\Users\"My name"\Desktop\DRM\widevine_keys-main>py -m pip install -r requirements.txt
Requirement already satisfied: xmltodict in c:\python38\lib\site-packages (from -r requirements.txt (line 1)) (0.12.0)
Requirement already satisfied: requests in c:\python38\lib\site-packages (from -r requirements.txt (line 2)) (2.25.1)
Requirement already satisfied: google in c:\python38\lib\site-packages (from -r requirements.txt (line 3)) (3.0.0)
Requirement already satisfied: google-api-python-client in c:\python38\lib\site-packages (from -r requirements.txt (line 4)) (2.9.0)
Requirement already satisfied: protobuf in c:\python38\lib\site-packages (from -r requirements.txt (line 5)) (3.17.3)
Requirement already satisfied: pycryptodome in c:\python38\lib\site-packages (from -r requirements.txt (line 6)) (3.10.1)
Requirement already satisfied: pycryptodomex in c:\python38\lib\site-packages (from -r requirements.txt (line 7)) (3.12.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python38\lib\site-packages (from requests->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\python38\lib\site-packages (from requests->-r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests->-r requirements.txt (line 2)) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: beautifulsoup4 in c:\python38\lib\site-packages (from google->-r requirements.txt (line 3)) (4.9.3)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (0.19.1)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (0.1.0)
Requirement already satisfied: six<2dev,>=1.13.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: google-api-core<2dev,>=1.21.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (1.30.0)
Requirement already satisfied: google-auth<2dev,>=1.16.0 in c:\python38\lib\site-packages (from google-api-python-client->-r requirements.txt (line 4)) (1.31.0)
Requirement already satisfied: packaging>=14.3 in c:\python38\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client->-r requirements.txt (line 4)) (20.9)
Requirement already satisfied: setuptools>=40.3.0 in c:\python38\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client->-r requirements.txt (line 4)) (41.2.0)
Requirement already satisfied: pytz in c:\python38\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client->-r requirements.txt (line 4)) (2021.1)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in c:\python38\lib\site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client->-r requirements.txt (line 4)) (1.53.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\python38\lib\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client->-r requirements.txt (line 4)) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\python38\lib\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client->-r requirements.txt (line 4)) (4.7.2)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\python38\lib\site-packages (from google-auth<2dev,>=1.16.0->google-api-python-client->-r requirements.txt (line 4)) (4.2.2)
Requirement already satisfied: pyparsing<3,>=2.4.2 in c:\python38\lib\site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client->-r requirements.txt (line 4)) (2.4.7)
Requirement already satisfied: soupsieve>1.2 in c:\python38\lib\site-packages (from beautifulsoup4->google->-r requirements.txt (line 3)) (2.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\python38\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2dev,>=1.16.0->google-api-python-client->-r requirements.txt (line 4)) (0.4.8)

C:\Users\"My name"\Desktop\DRM\widevine_keys-main>py -m pip install pycryptodome
Requirement already satisfied: pycryptodome in c:\python38\lib\site-packages (3.10.1)

C:\Users\"My name"\Desktop\DRM\widevine_keys-main>py -m pip install pycryptodomex
Requirement already satisfied: pycryptodomex in c:\python38\lib\site-packages (3.12.0)

C:\Users\"My name"\Desktop\DRM\widevine_keys-main>l3.py
Traceback (most recent call last):
  File "C:\Users\"My name"\Desktop\DRM\widevine_keys-main\l3.py", line 11, in <module>
    from cdm import cdm, deviceconfig
  File "C:\Users\"My name"\Desktop\DRM\widevine_keys-main\cdm\cdm.py", line 10, in <module>
    from cdm.formats import wv_proto2_pb2 as wv_proto2
  File "C:\Users\"My name"\Desktop\DRM\widevine_keys-main\cdm\formats\wv_proto2_pb2.py", line 20, in <module>
    _LICENSETYPE = DESCRIPTOR.enum_types_by_name['LicenseType']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'
```

![image](https://user-images.githubusercontent.com/88437066/145979558-be113561-1627-41e3-9fa5-a8a3ca3b30ff.png)

**Comment by KiahJane** [comment]
I am also experiencing the same problem and have not been able to find a solution.
