### ISSUE TITLE
Unable to parse and Session ID does not exist

### ISSUE THREAD

**Issue by eroffa** [medvm/widevine_keys#85]
Help me please. What is the reason for the error?

```bash
Input MPD URL: my url enter
License URL: my url enter

PSSH obtained.
my PSSH enter

unable to parse, unsupported init data format
unable to parse init data
session ID does not exist
Traceback (most recent call last):
  File "/home/user/Music/widevine_keys/l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
  File "/home/user/Music/widevine_keys/l3.py", line 41, in WV_Function
    request = b64encode(raw_request)
  File "/usr/lib/python3.10/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'int'

```

**Comment by medvm** [comment]
probably the server replied with some int error code
print(response) before base64 encoding it, also you can set a breakpoint and check variables state in the main scope.

**Comment by hamishegg** [comment]
Traceback (most recent call last):
  File "C:\Users\slipp\Downloads\widevine_keys-main\widevine_keys-main\l3.py", line 130, in <module>
    correct, keys = WV_Function(pssh, lic_url)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\slipp\Downloads\widevine_keys-main\widevine_keys-main\l3.py", line 39, in WV_Function
    wvdecrypt = WvDecrypt(init_data_b64=pssh, cert_data_b64=cert_b64, device=deviceconfig.device_android_generic)

same errors

**Comment by blueveno** [comment]
same errors
